### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by yogeshchandrark** [auto-mat/django-import-export-celery#1]
Hi,

I am trying to run the project file inside examples folder, before that i want to run the celery workers, so i tried to run the celery and i getting the below error.

I think i am getting from task.py file. can you please help.

TypeError: argument of type 'NoneType' is not iterable

I am using Python 3.7x
django 2.1.8

Regards,
Yogesh

**Comment by timthelion** [comment]
Hi,
can you please paste the whole command that you use to run celery as well as the full output?
Thanks

3. srpna 2019 11:38:17 SELČ, Yogesh Chandra Ramakrishna <notifications@github.com> napsal:

**Comment by yogeshchandrark** [comment]
Hi,

Thanks for the reply, i am trying in two OS (Windows and Ubuntu)

In windows i get the above mentioned error

(mydjango) C:\Users\Yogesh\Desktop\django-import-export-celery-master\example>celery -A project worker --loglevel=info

 -------------- celery@DESKTOP-S9EAUPN v4.3.0 (rhubarb)
---- **** -----
--- * ***  * -- Windows-10-10.0.18362-SP0 2019-08-03 22:47:21
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         apps.winners:0x1ec3367d2b0
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . import_export_celery.tasks.run_import_job

[2019-08-03 22:47:21,566: CRITICAL/MainProcess] Unrecoverable error: TypeError("argument of type 'NoneType' is not iterable")
Traceback (most recent call last):
  File "c:\anaconda3\envs\mydjango\lib\site-packages\celery\worker\worker.py", line 205, in start
    self.blueprint.start(self)
  File "c:\anaconda3\envs\mydjango\lib\site-packages\celery\bootsteps.py", line 119, in start
    step.start(parent)
  File "c:\anaconda3\envs\mydjango\lib\site-packages\celery\bootsteps.py", line 369, in start
    return self.obj.start()
  File "c:\anaconda3\envs\mydjango\lib\site-packages\celery\concurrency\base.py", line 131, in start
    self.on_start()
  File "c:\anaconda3\envs\mydjango\lib\site-packages\celery\concurrency\prefork.py", line 112, in on_start
    **self.options)
  File "c:\anaconda3\envs\mydjango\lib\site-packages\billiard\pool.py", line 1010, in __init__
    self._create_worker_process(i)
  File "c:\anaconda3\envs\mydjango\lib\site-packages\billiard\pool.py", line 1119, in _create_worker_process
    w.start()
  File "c:\anaconda3\envs\mydjango\lib\site-packages\billiard\process.py", line 124, in start
    self._popen = self._Popen(self)
  File "c:\anaconda3\envs\mydjango\lib\site-packages\billiard\context.py", line 383, in _Popen
    return Popen(process_obj)
  File "c:\anaconda3\envs\mydjango\lib\site-packages\billiard\popen_spawn_win32.py", line 47, in __init__
    spawn._Django_old_layout_hack__save()
  File "c:\anaconda3\envs\mydjango\lib\site-packages\billiard\spawn.py", line 81, in _Django_old_layout_hack__save
    project_dir = os.path.normpath(_module_parent_dir(project))
  File "c:\anaconda3\envs\mydjango\lib\site-packages\billiard\spawn.py", line 53, in _module_parent_dir
    dir, filename = os.path.split(_module_dir(mod))
  File "c:\anaconda3\envs\mydjango\lib\site-packages\billiard\spawn.py", line 60, in _module_dir
    if '__init__.py' in mod.__file__:
TypeError: argument of type 'NoneType' is not iterable

and in Ubuntu i get below error:
Error:
Unable to load celery application.
Module 'project' has no attribute 'celery'

i am using the below command in linux
 ` celery worker -A project --loglevel=debug --concurrency=4 `

and in window:
`celery -A project worker --loglevel=info`

Thanks,
Yogesh

**Comment by timthelion** [comment]
The correct command can be found in the docker compose file.
https://github.com/auto-mat/django-import-export-celery/blob/d30a4e3d1ea4ebd46a2ee2ff66e7374103d4e0ee/docker-compose.yaml#L20

The proper path for the celery settings module in this case is `project.celery`.

**Comment by yogeshchandrark** [comment]
Hi,

The above commond worked, i am able to run Celery now.

I will close this issue, its resolved.

Thank you for your time.

Regards,
Yogesh
