### ISSUE TITLE
Getting django.core.exceptions.ImproperlyConfigured error in Celery

### ISSUE THREAD

**Issue by yogeshchandrark** [auto-mat/django-import-export-celery#2]
Below is the complete error log in the Celery Server.

[2019-08-04 17:46:26,578: INFO/MainProcess] Received task: import_export_celery.tasks.run_import_job[cb18c31e-fee4-4072-be25-d46d07f0798b]
[2019-08-04 17:46:26,588: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f329f349400> (args:('import_export_celery.tasks.run_import_job', 'cb18c31e-fee4-4072-be25-d46d07f0798b', {'lang': 'py', 'task': 'import_export_celery.tasks.run_import_job', 'id': 'cb18c31e-fee4-4072-be25-d46d07f0798b', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'cb18c31e-fee4-4072-be25-d46d07f0798b', 'parent_id': None, 'argsrepr': '(2,)', 'kwargsrepr': "{'dry_run': True}", 'origin': 'gen1874@ubuntu-bionic', 'reply_to': '63856816-dad3-32bc-a9b9-c392f1929017', 'correlation_id': 'cb18c31e-fee4-4072-be25-d46d07f0798b', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}}, b'[[2], {"dry_run": true}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2019-08-04 17:46:26,598: INFO/ForkPoolWorker-4] import_export_celery.tasks.run_import_job[cb18c31e-fee4-4072-be25-d46d07f0798b]: Importing 2 dry-run True
[2019-08-04 17:46:26,631: DEBUG/MainProcess] Task accepted: import_export_celery.tasks.run_import_job[cb18c31e-fee4-4072-be25-d46d07f0798b] pid:2050
[2019-08-04 17:46:26,726: DEBUG/ForkPoolWorker-4] params: (2,)
[2019-08-04 17:46:26,727: DEBUG/ForkPoolWorker-4]
 sql_command: SELECT "import_export_celery_importjob"."id", "import_export_celery_importjob"."file", "import_export_celery_importjob"."processing_initiated", "import_export_celery_importjob"."imported", "import_export_celery_importjob"."format", "import_export_celery_importjob"."change_summary", "import_export_celery_importjob"."errors", "import_export_celery_importjob"."model", "import_export_celery_importjob"."author_id", "import_export_celery_importjob"."updated_by_id" FROM "import_export_celery_importjob" WHERE "import_export_celery_importjob"."id" = %(0)s
[2019-08-04 17:46:26,866: DEBUG/ForkPoolWorker-4] Find query: {'filter': {'id': {'$eq': 2}}, 'projection': ['id', 'file', 'processing_initiated', 'imported', 'format', 'change_summary', 'errors', 'model', 'author_id', 'updated_by_id']}
[2019-08-04 17:46:26,882: DEBUG/ForkPoolWorker-4] import_export_celery.tasks.run_import_job[cb18c31e-fee4-4072-be25-d46d07f0798b]: None
[2019-08-04 17:46:27,134: ERROR/ForkPoolWorker-4] Task import_export_celery.tasks.run_import_job[cb18c31e-fee4-4072-be25-d46d07f0798b] raised unexpected: ImproperlyConfigured()
Traceback (most recent call last):
  File "/home/vagrant/env/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/vagrant/env/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "../import_export_celery/tasks.py", line 61, in run_import_job
    result = resource.import_data(dataset, dry_run=dry_run)
  File "/home/vagrant/env/lib/python3.6/site-packages/import_export/resources.py", line 573, in import_data
    raise ImproperlyConfiguredNote:

django.core.exceptions.ImproperlyConfigured

its comming from the task.py file from the below mentioned code.

result = resource.import_data(dataset, dry_run=dry_run)

Note: I am using Vagrant not Dockers and i am using mongoDB

- logged in to Admin
- Uploaded the CSV file in examples folder
- Clicked on Save and Continue editting
- In Celery terminal i got the above error.

Thank you and Regards,
Yogesh

**Comment by timthelion** [comment]
Is this still with the example project or are you running your own code?

**Comment by yogeshchandrark** [comment]
Hi,

Yes,this is still with the example project, I am running example project inside Vagrant environment.

is this project configured only for dockers ?

I dont this its should be a problem.

**Comment by yogeshchandrark** [comment]
Hi,

any help on this, it will be very helpful.

Regards,
Yogesh

**Comment by timthelion** [comment]
currently the example project is tested only inside docker compose and you should use the docker-compose.yml as a reference for which commands to use to launch the project. A glance at the example projects settings.py file tells me that it is configured only for postgress. Either you already updated it, and in modifying the file you broke something and need to figure out what you broke, or you didn't update the file and you need to update it.

**Comment by yogeshchandrark** [comment]
Hi ,

It worked !!

I have just done one small modification in settings file and it is running.

And also i changed backend to poastgres(This should not be a issue, it should work with mongo also)

REDIS_HOST = 'localhost'
REDIS_PORT = '6379'
BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
REDIS_URL = os.environ.get('REDIS_URL', 'redis://redis')

It working fine.

Thanks you,
Yogesh

**Comment by yogeshchandrark** [comment]
closing this issue !
