### ISSUE TITLE
TypeError: NoneType takes no arguments

### ISSUE THREAD

**Issue by ewelinabuturla** [auto-mat/django-import-export-celery#36]
It happends to me randomly when starting export job. The job runs then when clicking on it (Run with Celery) once again in `ExportJobs` in Django Admin. Any ideas?

```
2021-02-23T06:17:09.585791+00:00 app[worker.1]: [2021-02-22 22:17:09,585: ERROR/ForkPoolWorker-7] Task import_export_celery.tasks.run_export_job[6bbc3607-6179-4ab6-b3e1-a23bb82eb4c4] raised unexpected: TypeError('NoneType takes no arguments')
2021-02-23T06:17:09.585792+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-23T06:17:09.585793+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
2021-02-23T06:17:09.585793+00:00 app[worker.1]:     R = retval = fun(*args, **kwargs)
2021-02-23T06:17:09.585794+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
2021-02-23T06:17:09.585794+00:00 app[worker.1]:     return self.run(*args, **kwargs)
2021-02-23T06:17:09.585794+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 171, in _inner
2021-02-23T06:17:09.585794+00:00 app[worker.1]:     reraise(*exc_info)
2021-02-23T06:17:09.585795+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise
2021-02-23T06:17:09.585795+00:00 app[worker.1]:     raise value
2021-02-23T06:17:09.585796+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 166, in _inner
2021-02-23T06:17:09.585796+00:00 app[worker.1]:     return f(*args, **kwargs)
2021-02-23T06:17:09.585796+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/import_export_celery/tasks.py", line 199, in run_export_job
2021-02-23T06:17:09.585797+00:00 app[worker.1]:     class Resource(resource_class):
2021-02-23T06:17:09.585797+00:00 app[worker.1]: TypeError: NoneType takes no arguments
```

**Comment by timthelion** [comment]
What a bizare stack trace, anyone got any ideas how that error could be triggered by the line `class Resource(resource_class)`? I'm almost inclined to think that some bug somewhere has scrambled the backtrace. The only thing that occures to me, is that there may,be some code in a metaclass of your resource class which is running when the resouce class is inherited.

**Comment by ewelinabuturla** [comment]
This is how my resource looks like:

```
 class CeleryVideoResource(BaseVideoResource):              
    user_name = Field()                                                                           
    video_str = Field()

    def dehydrate_user_name(self, event):                                                         
        user = None
        if event.video.user:                                                                      
            user = f"{event.video.user.first_name} {event.video.user.last_name}"                  
        return user
        
       def dehydrate_video_str(self, event):                                                         
         return event.video.__str__()                                                              

     class Meta:                                            
         model = Video                                      
         fields = (                                         
             "id",                                          
             "name",                                        
             "user_name",                                   
             "times_started",                               
             "times_watched",                               
         )                                                
```  

And Im exporting it like that:
```
@classmethod
def export_resource_classes(cls):
    from whimsifull_api.video.resources import CeleryVideoResource

    return {
        "videos": ("Videos resource", CeleryVideoResource),
    }

```

**Comment by timthelion** [comment]
I'll be honest, I really don't know. However, I've been googling wrong stack traces and it seems they are possible https://stackoverflow.com/questions/58311448/unexpected-line-given-when-python-interpreter-reports-exception. I also know, that task serialization on older versions of celery is weird and generally celery instancesneed to be resarted when debugging, to _make shure code is consistent across instances_. It ispossible for your main app and celery to berunning different versions of the code and this can leed to all sorts of debugging hell. Basically, I'm telling you to try restarting celery if you haven't already.

**Comment by vincentleeuwen** [comment]
@ewelinabuturla having this issue as well. did you find a solution in the end?

**Comment by aparakian** [comment]
This is so mind boggling, I'm having the same issue and I'm not using an old version of celery (4.4.7). Each time I restart celery, the first export works, then it really varies...

**Comment by spiria-sayeghr** [comment]
Also having this issue.

**Comment by timthelion** [comment]
So who's going to to take the initiative and go try to ask the fine folks at the celery project and or python project for help? I really have no clue at all.

**Comment by timthelion** [comment]
Allegedly fixed.

**Comment by nichoski** [comment]
This is not fixed. The error is caused by the job's resource attribute being None. I'm not sure where this attribute is supposed to be populated. The [create_export_job_action](https://github.com/auto-mat/django-import-export-celery/blob/master/import_export_celery/admin_actions.py#L42) method creates an export job without setting the resource attribute. And if this attribute is empty, the get_resource_class method returns None, which the export task tries to use to create a resource class using `class Resource(resource_class):`.

**Comment by ssyberg** [comment]
I'm experiencing this on celery 5.2.3 and django-import-export-celery 1.6

**Comment by ssyberg** [comment]
Interesting, turning off the email toggle fixed this for me!
